name: Deploy to dev

on:
  push:
    branches: [develop]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Pulumi up
        uses: ./.github/actions/pulumi-up
        with:
          pulumi-azure-storage-account: ${{ secrets.PULUMI_AZURE_STORAGE_ACCOUNT }}
          pulumi-azure-storage-key: ${{ secrets.PULUMI_AZURE_STORAGE_KEY }}
          pulumi-stack: demo-azure-cdn-dev
          pulumi-stack-passphrase: ${{ secrets.PULUMI_STACK_PASSPHRASE }}
