name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: pulumi up
        uses: docker://pulumi/actions
        with:
          args: up --skip-preview
        env:
          # Voir https://github.com/pulumi/pulumi/blob/master/docker/actions/entrypoint.sh
          # Backend
          PULUMI_BACKEND_URL: --cloud-url azblob://pulumi
          AZURE_STORAGE_ACCOUNT: frpol9build
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

          # Unlock stack
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}

          # Connect to Azure
          ARM_SUBSCRIPTION_ID: 792a7eaf-b31d-469c-beaf-fc2f288c70fc
          ARM_CLIENT_ID: ae874ae3-5423-445a-bc29-28bed0ebd661
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: 56778bd5-6a3f-4bd3-a265-93163e4d5bfe
          
          # Permet à l'action de faire différente logique préalable à l'exécution
          PULUMI_CI: up