name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Pour avoir accès à des variables plus simples comme GITHUB_REF_SLUG_URL
      - name: GitHub Slug Action
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install
        run: npm ci
