name: Deploy

on:
  push:
    branches: main
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pulumi up
        uses: ./.github/actions/pulumi-up
        with:
          stack: demo-azure-cdn-dev
          azure-storage-key: ${{ secrets.AZURE_STORAGE_KEY }}
          passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_DEV }}
