name: Promote to prod

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: prod

      - name: Fetch app
        run: git fetch origin app

      - name: Merge Fast-Forward 
        run: git merge --ff refs/remotes/origin/app
      
      - name: Push changes
        run: git push

      - name: Pulumi up
        uses: ./.github/actions/pulumi-up
        with:
          stack: demo-azure-cdn-prod
          azure-storage-key: ${{ secrets.AZURE_STORAGE_KEY }}
          passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE_PROD }}